version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: darsi_icd10_db
    environment:
      POSTGRES_DB: darsi_icd10
      POSTGRES_USER: darsi
      POSTGRES_PASSWORD: darsi
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: